#! /bin/bash

# Tell if debian based {{{
cd /etc/apt 2> /dev/null
if [ $? -eq 0 ]; then
    sudo apt update -y
    sudo apt upgrade -y
    sudo apt autoremove -y
    sudo apt autoclean -y
    sudo apt install vim -y
    sudo apt install tmux -y
    sudo apt install tree -y
    sudo apt install wget -y
    sudo apt install fish -y
    sudo apt install git -y
    sudo apt install bash-completion -y
    sudo apt install ssh -y
    sudo apt install htop -y
    sudo apt install curl -y
    sudo apt install wget -y
    sudo apt install cron -y
    sudo apt install lazygit -y
    # Move these to a coding install list?
    sudo apt install gcc -y
    # sudo apt install -y
fi
# }}}

# Tell if rpm or redhat {{{
cd /etc/rpm 2> /dev/null
if [ $? -eq 0 ]; then
    sudo dnf install tree
    sudo dnf install wget
    sudo dnf install github
    # sudo dnf install
fi
# }}}

# Tell if arch based {{{
cd /etc/pacman.d 2> /dev/null
if [ $? -eq 0 ]; then
    sudo pacman -Syu vim
    sudo pacman -Sy tmux
    sudo pacman -Sy tree
    sudo pacman -Sy wget
    sudo pacman -Sy fish
    sudo pacman -Sy git
    sudo pacman -Sy ssh
    sudo pacman -Sy htop
    sudo pacman -Sy yay
    echo 1 | yay lazygit  # Untested so far
    # sudo pacman -Sy
fi
# }}}

# Github clone/set-url {{{
    git clone https://github.com/IntrovertedCoder/dotconfig ~/.config/dots
    set cwd $PWD
    cd ~/.config/dots
    git remote set-url origin git@github.com:IntrovertedCoder/dotconfig.git
    cd $cwd
# }}}

# Copying config files {{{
    rm ~/.config/fish
    ln -s ~/.config/dots/fish ~/.config/fish
    rm ~/.vim
    ln -s ~/.config/dots/vim/vim ~/.vim
    rm ~/.vimrc
    ln -s ~/.config/dots/vim/vimrc ~/.vimrc
    rm ~/.tmux.conf
    ln -s ~/.config/dots/tmux/.tmux.conf ~/.tmux.conf
    # sudo commands {{{
        sudo ln -s ~/.config/dots/bin/googler /bin/googler
        sudo ls -s ~/.config/dots/scripts/scan /bin/scan
    # }}}
# }}}

# Set default stuff {{{
export EDITOR="vim"
# }}}

# ssh keys {{{
    ssh-keygen -t rsa -b 4096 -f ~/.ssh/github -q -N ''
# }}}

# Set shell
chsh -s /usr/bin/fish
