#! /bin/bash

center(){
    COLUMNS=$(tput cols)
    title="$*"
    tput setaf 81; printf "%*s\n" $(((${#title}+$COLUMNS)/2)) "$title"; tput sgr0
}

# Tell if debian based {{{
cd /etc/apt 2> /dev/null
if [ $? -eq 0 ]; then
    center "UPDATE"
    sudo apt update -y
    center "UPGRADE"
    sudo apt upgrade -y
    center "AUTOREMOVE"
    sudo apt autoremove -y
    center "AUTOCLEAN"
    sudo apt autoclean -y
    center "vim"
    sudo apt install vim -y
    center "tmux"
    sudo apt install tmux -y
    center "tree"
    sudo apt install tree -y
    center "wget"
    sudo apt install wget -y
    center "fish"
    sudo apt install fish -y
    center "git"
    sudo apt install git -y
    center "bash-completion"
    sudo apt install bash-completion -y
    center "ssh"
    sudo apt install ssh -y
    center "htop"
    sudo apt install htop -y
    center "curl"
    sudo apt install curl -y
    center "wget"
    sudo apt install wget -y
    center "cron"
    sudo apt install cron -y
    center "lazygit"
    sudo apt install lazygit -y
    center "youtube-dl"
    sudo apt install youtube-dl -y
    # sudo apt install -y
fi
# }}}

# Tell if rpm or redhat {{{
cd /etc/rpm 2> /dev/null
if [ $? -eq 0 ]; then
    sudo dnf install tree
    sudo dnf install wget
    sudo dnf install github
    # sudo dnf install
fi
# }}}

# Tell if arch based {{{
cd /etc/pacman.d 2> /dev/null
if [ $? -eq 0 ]; then
    center "UPDATE"
    sudo pacman -Syu
    center "vim"
    sudo pacman -Syu vim
    center "tmux"
    sudo pacman -Sy tmux
    center "tree"
    sudo pacman -Sy tree
    center "wget"
    sudo pacman -Sy wget
    center "fish"
    sudo pacman -Sy fish
    center "git"
    sudo pacman -Sy git
    center "ssh"
    sudo pacman -Sy openssh
    center "htop"
    sudo pacman -Sy htop
    center "yay"
    sudo pacman -Sy yay
    center "lazygit (AUR)"
    echo 1 | yay lazygit  # Untested so far
    # sudo pacman -Sy
fi
# }}}

# Github clone/set-url {{{
    git clone https://github.com/IntrovertedCoder/dotconfig ~/.config/dots
    set cwd $PWD
    cd ~/.config/dots
    git remote set-url origin git@github.com:IntrovertedCoder/dotconfig.git
    cd $cwd
# }}}

# Copying config files {{{
    rm ~/.config/fish
    ln -s ~/.config/dots/fish ~/.config/fish
    rm ~/.vim
    ln -s ~/.config/dots/vim/vim ~/.vim
    rm ~/.vimrc
    ln -s ~/.config/dots/vim/vimrc ~/.vimrc
    rm ~/.tmux.conf
    ln -s ~/.config/dots/tmux/.tmux.conf ~/.tmux.conf
    rm ~/.config/fish
    ln -s ~/.config/dots/fish ~/.config/fish
    # sudo commands {{{
        sudo ln -s ~/.config/dots/bin/googler /bin/googler
        sudo ls -s ~/.config/dots/scripts/scan /bin/scan
    # }}}
# }}}

# Set default stuff {{{
export EDITOR="vim"
# }}}

# ssh keys {{{
    ssh-keygen -t rsa -b 4096 -f ~/.ssh/github -q -N ''
# }}}

# Set shell
chsh -s /usr/bin/fish
