# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Remove the first newline of the prompt
add_newline = false

right_format = """$status $memory_usage $cmd_duration $sudo"""

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](#4CC700)"
error_symbol = "[✗](#C7000C)"

[git_branch]
truncation_length = 4
truncation_symbol = ""
ignore_branches = ["master", "main"]

[git_commit]
commit_hash_length = 4

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = '[=/($count\)](#C7000C)'
ahead = '[⇡\($count\)](#7E599D)'
behind = '[⇣\($count\)](#9C000A)'
diverged = '[⇕\($count\)](#949494)'
up_to_date = '[✓\($count\)](#0B68FF)'
untracked = '[?\($count\)](#6A7AB4)'
stashed = '[$\($count\)](#7E599D)'
modified = '[!\($count\)](#D8CE08)'
staged = '[+\($count\)](#4CC700)'
renamed = '[»\($count\)](#D0670A)'
deleted = '[✘\($count\)](#FF0B1B)'

[python]
symbol = ""

[directory]
read_only = ""
format = "[$path ](#0B68FF)[$read_only](#C7000C) "
truncation_length = 16
truncation_symbol = "…/"

[sudo]
format = "[](#D0670A)"
disabled = false

[cmd_duration]
min_time = 500
format = "[ $duration](#D8CE08)"

[container]
format = "[ \\[$name\\]](#7E599D)"

[hostname]
format = "[$hostname](#7E599D) in "
disabled = false

[memory_usage]
disabled = false
threshold = -1
format = "[ $ram](#3C5B33)"

[status]
symbol = ""
success_symbol = ""
not_found_symbol = ""
sigint_symbol = ""
not_executable_symbol = ""
format = '[\($symbol$common_meaning$signal_name$maybe_int\)](#101010)'
map_symbol = true
disabled = false
