#! /bin/bash
VAR=$*
if ((${#VAR} > 0)); then
	git add .
	git commit -m "$VAR"
	git push -u origin master
else
	yymmdd=$(date +"%y %m %d")
	git add .
	git commit -m "$yymmdd"
	git push -u origin master
fi
