#! /bin/bash

set cwd $PWD
rm .files
cpulimit --limit=2 -i du -ha --time=ctime --exclude={.git,.cache,/home/arik/.cargo} / 1> ~/.files 2> /dev/null
rm ~/files
cpulimit --limit=2 -i du -a --time=ctime --exclude={.git,.cache,/home/arik/.cargo} / 1> ~/.files 2> /dev/null
mv ~/.files ~/files
cd $cwd
