#!/bin/python3.8
import os  # Used for running terminal commands from python
import sys  # Used for sys.argv

# Deleting the first sys.argv (sys.argv[0] is where it was run from)
args = sys.argv[1:]

# Running each arg
for arg in args:
    os.system('firefox ' + arg)
